### ISSUE TITLE
Django Integration: Documentation and URL handling

### ISSUE THREAD

**Issue by RyanRio** [bokeh/bokeh-django#4]
Created from discussion around [this discourse topic](https://discourse.bokeh.org/t/configuration-of-bokeh-channels-integration/4643/4).

The main feature I am interested in is properly using `autoload` from `bokeh.server.django` to access a bokeh app without mangling the url in the request function. To demonstrate this, consider the django project named `project` and just using views/urls within said project directory (this could easily be extended to be contained within an app). Currently the following has to be done in order to support the generic 'title':

```python
# in urls.py within the project directory
bokeh_apps = [
    autoload("home/x", views.app_handler),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/<str:title>", views.app),
]

# in views

def app(request: HttpRequest, title) -> HttpResponse:
    script = server_document(request.build_absolute_uri("/home/x"), arguments={"title": title}) # breaks the django url
    return render(request, "embed.html", dict(script=script))

def app_handler(doc: Document) -> None:
    df = sea_surface_temperature.copy()
    source = ColumnDataSource(data=df)
    plot = figure(x_axis_type="datetime", y_range=(0, 25), y_axis_label="Temperature (Celsius)",
                  title="Sea Surface Temperature at 43.18, -70.43")
    plot.line("time", "temperature", source=source)

    doc.add_root(column(slider, plot))
   # taken from examples and simplified

# and then in routing.py
bokeh_app_config = apps.get_app_config('bokeh.server.django')

application = ProtocolTypeRouter({
    'websocket': AuthMiddlewareStack(URLRouter(bokeh_app_config.routes.get_websocket_urlpatterns())),
    'http': AuthMiddlewareStack(URLRouter(bokeh_app_config.routes.get_http_urlpatterns())),
})
```

Ideally, you could indicate to autoload that it will take a parameter and it would make that parameter available to that handler. Note that it is already technically available to the handler under doc.session_context.arguments, however I still had to explicitly put "/home/x"

A few issues from this example:
1. In order to set this up you explicitly define the url that bokeh will set up it's WSConsumer and AutoloadJSConsumer, in this case "home/x/ws" and "home/x/'autoloadjsurl'".
2. It's largely a pain as far as I can tell to actually do anything with the WSConsumer, for instance you can technically inherit WSConsumer like so:
```python
class Wrapper(WSConsumer):

def __init__(self, scope: Dict[str, Any]):
    super().__init__(scope)

async def connect(self):
    await super().connect()
    print("connecting") # add your own code wherever you want here, and just forward along bokeh information

async def disconnect(self, close_code):
    await super().disconnect(close_code)

async def receive(self, text_data):
    await super().receive(text_data)
```
and substitute it into `django/routing.py` in `add_new_routing(...)`:
`self._websocket_urlpatterns.append(url(urlpattern("/ws"), Wrapper, kwargs=kwargs))`
3. Documentation is lacking all around here, for instance what is the difference/the use cases between `DocConsumer (document())` and `AutoloadJsConsumer (autoload)`

If a full project directory is required I will happily provide, but I think that this is mainly a documentation issue - I am happy to contribute!

This is on bokeh version 1.4.0, I looked at the recent commit bokeh/bokeh#9536 but that seemed to have just added token support so what I have put here should be up to date, at least concerning what I am discussing here!

**Comment by sdc50** [comment]
@RyanRio 

Take a look at PR #6 and let me know if you have any feedback.

Here are the key points from the expanded examples in the PR:

`urls.py`
```python
urlpatterns = [
    path("shapes/<str:arg1>/<str:arg2>", views.shapes_with_args),
]

bokeh_apps = [
    autoload("shapes/(?P<arg1>[\w_\-]+)/(?P<arg2>[\w_\-]+)", views.shape_viewer_handler_with_args),
]
```

Note that `autoload` takes a `re_path` pattern.

`views.py`

```python
from bokeh_django import with_url_args

@with_url_args
def shape_viewer_handler_with_args(doc, arg1, arg2):
    viewer = shape_viewer()
    pn.Column(
        viewer,
        pn.pane.Markdown(f'## This app has URL Args: {arg1} and {arg2}')
    ).server_doc(doc)

def shapes_with_args(request: HttpRequest, arg1: str, arg2: str) -> HttpResponse:
    script = server_document(request.get_full_path())
    return render(request, "embed.html", dict(script=script))
```

Note that `server_document` should be called with `request.get_full_path()`.
